# Generated by Django 5.1.4 on 2025-01-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_firstname', models.CharField(max_length=200)),
                ('spec', models.CharField(max_length=120)),
                ('staj', models.CharField(max_length=120)),
                ('img', models.ImageField(upload_to='teacher/')),
            ],
            options={
                'verbose_name': 'Мугалимдер',
                'verbose_name_plural': 'Мугалимдер',
            },
        ),
    ]
