# Generated by Django 5.1.4 on 2025-01-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeestTcOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_old_tc', models.CharField(max_length=250, verbose_name='ФИО Пред. оп')),
                ('content_old_tc', models.TextField(blank=True, null=True, verbose_name='Описание необезательно')),
                ('years_old_tc', models.CharField(max_length=20, verbose_name='годами работали')),
                ('srec_old_tc', models.CharField(max_length=20, verbose_name='Специалист')),
                ('img_old_tc', models.ImageField(blank=True, null=True, upload_to='best_teacher_old/', verbose_name='Фото необ.')),
            ],
            options={
                'verbose_name': 'Эмгек синирген мугалимдер',
                'verbose_name_plural': 'Эмгек синирен мугалимдер',
            },
        ),
        migrations.CreateModel(
            name='BestGr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_gr', models.CharField(max_length=250, verbose_name='ФИО выпускника')),
                ('content_gr', models.TextField(blank=True, null=True, verbose_name='Описние необ.')),
                ('year_gr', models.CharField(max_length=8, verbose_name='Год выпуска')),
                ('img_gr', models.ImageField(blank=True, null=True, upload_to='best_gr/', verbose_name='Фото необ.')),
            ],
            options={
                'verbose_name': 'Успешные выпускники',
                'verbose_name_plural': 'Успешные выпускники',
            },
        ),
        migrations.CreateModel(
            name='BestSt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_st', models.CharField(max_length=250, verbose_name='ФИО ученика')),
                ('content_st', models.TextField(blank=True, null=True, verbose_name='Контент необ.')),
                ('klass_st', models.IntegerField(default=1, verbose_name='Класс')),
                ('img_st', models.ImageField(blank=True, null=True, upload_to='best_st/', verbose_name='Фото необ.')),
            ],
            options={
                'verbose_name': 'Мыкты окуучулар',
                'verbose_name_plural': 'Мыкты окуучулар',
            },
        ),
        migrations.CreateModel(
            name='EduMatCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ed', models.CharField(max_length=255, verbose_name='Учебный мет. ком.')),
                ('content_ed', models.TextField(blank=True, null=True, verbose_name='контент необ.')),
                ('img_ed', models.ImageField(blank=True, null=True, upload_to='edumatcom/', verbose_name='фото необ.')),
            ],
            options={
                'verbose_name': 'Уч. мет. ком.',
                'verbose_name_plural': 'Уч. мет. ком.',
            },
        ),
        migrations.CreateModel(
            name='Olimpiada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ol', models.CharField(max_length=250, verbose_name='Заголовка')),
                ('content_ol', models.TextField(blank=True, null=True, verbose_name='Описание необ.')),
                ('img_ol', models.ImageField(blank=True, null=True, upload_to='olimpiada/', verbose_name='фото необ.')),
            ],
            options={
                'verbose_name': 'Олимпиада',
                'verbose_name_plural': 'Олимпиада',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sp', models.CharField(max_length=255, verbose_name='Заголовка спорт')),
                ('content_sp', models.TextField(blank=True, null=True, verbose_name='Описание необ.')),
                ('img_sp', models.ImageField(blank=True, null=True, upload_to='olimpiada/', verbose_name='фото необ.')),
            ],
            options={
                'verbose_name': 'Спорт',
                'verbose_name_plural': 'Спорт',
            },
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': 'Картина', 'verbose_name_plural': 'Каритины'},
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='news/'),
        ),
    ]
