# Generated by Django 5.1.4 on 2025-01-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_beesttcold_bestgr_bestst_edumatcom_olimpiada_sport_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeestTcOld',
            new_name='BestTcOld',
        ),
    ]
