# Generated by Django 5.1.4 on 2025-01-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_beesttcold_besttcold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
