# Generated by Django 5.1.4 on 2025-01-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestgr',
            name='img_gr',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='best_gr/', verbose_name='Фото необ.'),
        ),
        migrations.AlterField(
            model_name='bestst',
            name='img_st',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='best_st/', verbose_name='Фото необ.'),
        ),
        migrations.AlterField(
            model_name='besttcold',
            name='img_old_tc',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='best_teacher_old/', verbose_name='Фото необ.'),
        ),
        migrations.AlterField(
            model_name='edumatcom',
            name='img_ed',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='edumatcom/', verbose_name='фото необ.'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(default='default.png', upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='olimpiada',
            name='img_ol',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='olimpiada/', verbose_name='фото необ.'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='img_sp',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='olimpiada/', verbose_name='фото необ.'),
        ),
    ]
