# Generated by Django 5.1.4 on 2025-01-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bestgr_img_gr_alter_bestst_img_st_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.ImageField(default='default.png', upload_to='teacher/'),
        ),
    ]
