# Generated by Django 5.1.4 on 2024-12-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовка')),
                ('content', models.TextField(verbose_name='Контент')),
                ('data_create', models.DateField(auto_now=True, verbose_name='Дата создание')),
            ],
        ),
    ]
