# Generated by Django 5.1.4 on 2024-12-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='content_full',
            field=models.TextField(default=234, verbose_name='полный контент'),
            preserve_default=False,
        ),
    ]
